rem GRINNELL SPACE EXPLORATION AGENCY
rem Near-Space Balloon Project Camera Control

@title Near-Space Balloon Project Camera Control

rem x is the time between shots in ms
x = 5000
rem t is the video length in ms
t = 20000
rem y is the count of images taken
y = 0

:main
goto "image"

:image
sleep x
shoot
y = y + 1
if y = 10 then goto "video"
goto "image"

:video
press "video"
sleep t
release "video"
y = 0
goto "image"
